stature_association_ui <- tabPanel("Stature Association",icon = icon("chart-line", lib="font-awesome"),
    sidebarLayout(
        sidebarPanel(
            fluidRow(
                column(12,
		            selectizeInput(inputId = "reference_select_as", label = "Reference", choices = c("DPAA Black Males", "DPAA White Males", "Trotter Black Males", "Trotter White Males", "CMNH White Males", "CMNH Black Males", "SI-Terry White Males", "SI-Terry Black Males", "UT White Males", "UT Black Males"), multiple = TRUE, selected = "DPAA White Males"), # "DPAA Black Males", "DPAA White Males", "DPAA White Females", "DPAA Black Females", "DPAA Pacific Islander Males", "DPAA Mexican Males", "DPAA Mexican Females", "DPAA Korean Males", "DPAA Korean Females", "DPAA Japanese Males", "DPAA Japanese Females", "DPAA Chinese Males", "DPAA Chinese Females", "DPAA Cambodian Males", "DPAA Asian Males", "DPAA Asian Females", "DPAA American Indian Males", "DPAA Hispanic Males"), multiple = TRUE, selected = "Trotter White Males"),
                ),
                column(12,
                    radioButtons(inputId = "prediction_interval_as", label = "Prediction Interval", inline=TRUE, choices = c("90%", "95%", "99%"), selected = "95%")
                ),
                column(12,
                    radioButtons(inputId = "metric_as", label = "Stature Metric", inline=TRUE, choices = c("Inches", "Centimeters"), selected = "Inches")
                ),
                column(12,
                    numericInput(inputId = "known_stature_as", label = "Known Stature", value = "", min=0,max=999,step=0.01)
                ),
                column(6,
                    selectInput(inputId = "bone_as", label = "Bone", c("humerus","ulna","radius","femur","tibia","fibula"))
                ),
                column(6,
                    selectInput("bone_side_as", "Side", c("left","right"))
                ),
                column(12,
                    conditionalPanel(condition = "input.bone_as == 'humerus'",
                        bsTooltip("Hum_01_as", "Maximum Length of the Humerus: The distance from the most superior point on the head of the humerus to the most inferior point on the trochlea (Moore-Jansen et al. 1994, #40; Langley et al. 2016:74, #45)", trigger = "hover"),
                        bsTooltip("Hum_02_as", "Epicondylar Breadth of the Humerus: The distance from the most laterally protruding point on the lateral epicondyle to the corresponding projection on the medial epicondyle (Moore-Jansen et al. 1994, #41; Langley et al. 2016:74, #46)", trigger = "hover"),
                        bsTooltip("Hum_03_as", "Maximum Vertical Diameter of Head: The distance between the most superior and inferior points on the border of the articular surface (Moore-Jansen et al. 1994, #42; Langley et al. 2016:74, #47)", trigger = "hover"),
                        bsTooltip("Hum_04_as", "Maximum Diameter of the Humerus at Midshaft: The maximum diameter of the humeral shaft at midshaft (Moore-Jansen et al. 1994, #43; Langley et al. 2016:74-75, #48)", trigger = "hover"),
                        bsTooltip("Hum_05_as", "Minimum Diameter of the Humerus at Midshaft: The minimum diameter of the humeral shaft at midshaft (Moore-Jansen et al. 1994, #44; Langley et al. 2016:75, #49)", trigger = "hover"),
                        bsTooltip("Hum_06_as", "Total Breadth of the Capitulum-Trochlea: The breadth of the capitulum and trochlea at the distal humerus. One end of the sliding calipers is positioned parallel to the flat, spool-shaped surface of the trochlea (medial), and the other end is moved until it comes into contact with the capitulum (lateral) (Byrd and Adams 2003, #41A)", trigger = "hover"),
                        bsTooltip("Hum_07_as", "Anterior-Posterior Breadth of the Head: The maximum breadth of the humeral head taken in the anterior-posterior direction on the articular surface.  This measurement is taken perpendicular from the vertical diameter of the humeral head (Byrd and Adams 2003, #42A)", trigger = "hover"),
                        bsTooltip("Hum_08_as", "Minimum Diameter of the Diaphysis: The minimum diameter of the humeral diaphysis taken in any direction perpendicular to the shaft.  This measurement should be taken on the oval part of the shaft, superior to the flattening observed around the olecranon fossa and the lateral supracondylar ridge. Often it is found near midshaft (Byrd and Adams 2003, #44B)", trigger = "hover"),
                        bsTooltip("Hum_09_as", "Maximum Diameter of Diaphysis at the Deltoid Tuberosity: The maximum diameter of the diaphysis within the length of the deltoid tuberosity. Rotate and slide the element to find the maximum diameter (Byrd and Adams 2015, #44D)", trigger = "hover"),
                        numericInput("Hum_01_as", label = "Hum_01", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_02_as", label = "Hum_02", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_03_as", label = "Hum_03", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_04_as", label = "Hum_04", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_05_as", label = "Hum_05", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_06_as", label = "Hum_06", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_07_as", label = "Hum_07", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_08_as", label = "Hum_08", value = "", min=0,max=999,step=0.01),
                        numericInput("Hum_09_as", label = "Hum_09", value = "", min=0,max=999,step=0.01)
                    ),
                    conditionalPanel(condition = "input.bone_as == 'ulna'",
                        bsTooltip("Uln_01_as", "Maximum Length of the Ulna: The distance between the most proximal point on the olecranon and the most distal point on the styloid process (Moore-Jansen et al. 1994, #48; Langley et al. 2016:75-76, #54)", trigger = "hover"),
                        bsTooltip("Uln_02_as", "Maximum Midshaft Diameter of the Ulna: The maximum diameter of the diaphysis at midshaft (Moore-Jansen et al. 1994, #48; Langley et al. 2016:75-76, #54) ", trigger = "hover"),
                        bsTooltip("Uln_03_as", "Minimum Midshaft Diameter of the Ulna: The minimum diameter of the diaphysis at midshaft (Langley et al. 2016:76, #56)", trigger = "hover"),
                        bsTooltip("Uln_04_as", "Dorso-Volar (Anterior-Posterior) Diameter: The maximum diameter of the diaphysis where the crest exhibits the greatest development in the anterior-posterior (dorso-volar) plane (Moore-Jansen et al. 1994, #49)", trigger = "hover"),
                        bsTooltip("Uln_05_as", "Transverse (Medial-Lateral) Diameter: The distance between medial and lateral surfaces at the level of greatest crest development (Moore-Jansen et al. 1994, #50)", trigger = "hover"),
                        bsTooltip("Uln_06_as", "Physiological Length of the Ulna: The distance between the deepest point on the articular surfaceof the coronoid process on the guiding ridge and the most inferior point on the distal articular surface of the ulna (Moore-Jansen et al. 1994, #51)", trigger = "hover"),
                        bsTooltip("Uln_08_as", "Olecranon Breadth: The maximum breadth of the olecranon process, taken perpendicular to the longitudinal axis of the semilunar notch (Langley et al. 2016:76, #59)", trigger = "hover"),
                        bsTooltip("Uln_09_as", "Minimum Diameter of the Diaphysis including Interosseous Crest: Locate the minimum diameter of the diaphysis along the portion of the bone that includes the interosseous crest. This measurement may not necessarily include the interosseous crest, but should be taken on that part of the shaft that exhibits the crest. This measurement is not always near the distal end of the crest (Byrd and Adams 2003, #51A)", trigger = "hover"),
                        bsTooltip("Uln_10_as", "Minimum Diameter of the Diaphysis: This measurement will be found near the distal epiphysis of the ulna. The bone should be rotated in order to locate the minimum distance (Byrd and Adams 2003, #51B)", trigger = "hover"),
                        bsTooltip("Uln_11_as", "Breadth of the Semilunar Notch: This is a measure of only the distal surface of the semilunar notch (the base) (Byrd and Adams 2003, #51C)", trigger = "hover"),
                        numericInput("Uln_01_as", label = "Uln_01", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_02_as", label = "Uln_02", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_03_as", label = "Uln_03", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_04_as", label = "Uln_04", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_05_as", label = "Uln_05", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_06_as", label = "Uln_06", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_08_as", label = "Uln_08", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_09_as", label = "Uln_09", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_10_as", label = "Uln_10", value = "", min=0,max=999,step=0.01),
                        numericInput("Uln_11_as", label = "Uln_11", value = "", min=0,max=999,step=0.01)
                    ),
                    conditionalPanel(condition = "input.bone_as == 'radius'",
                        bsTooltip("Rad_01_as", "Maximum Length of the Radius: The distance from the most proximally positioned point on the head of the radius to the tip of the styloid process without regard to the long axis of the bone (Moore-Jansen et al. 1994, #45; Langley et al. 2016:75, #50)", trigger = "hover"),
                        bsTooltip("Rad_02_as", "Maximum Diameter of the Radius at Midshaft: The maximum diameter of the radial shaft taken at midshaft (Langley et al. 2016:75, #51)", trigger = "hover"),
                        bsTooltip("Rad_03_as", "Minimum Diameter of the Radius at Midshaft: The minimum diameter of the radial shaft taken at midshaft (Langley et al. 2016:75, #52)", trigger = "hover"),
                        bsTooltip("Rad_04_as", "Maximum Diameter of the Head: The maximum diameter of the radial head measured on the margin of the head that articulates with the ulna. The bone is rotated until the maximum distance is obtained (Langley et al. 2016:75, #53; Byrd and Adams 2003, #47D)", trigger = "hover"),
                        bsTooltip("Rad_05_as", "Sagittal (Anterior-Posterior) Diameter at Midshaft: The distance between anterior and posterior surfaces at midshaft (Moore-Jansen et al. 1994, #46)", trigger = "hover"),
                        bsTooltip("Rad_06_as", "Transverse (Medial-Lateral) Diameter at Midshaft: The distance between medial and lateral surfaces at midshaft (Moore-Jansen et al. 1994, #47)", trigger = "hover"),
                        bsTooltip("Rad_07_as", "Maximum Diameter at the Radial Tuberosity: The maximum shaft diameter on the radial tuberosity.  Position the calipers around the tuberosity and rotate the bone until the maximum distance is obtained (Byrd and Adams 2003, #47A)", trigger = "hover"),
                        bsTooltip("Rad_08_as", "Maximum Diameter of the Diaphysis Distal to the Radial Tuberosity: The maximum shaft diameter distal to the radial tuberosity, positioned along the interosseous crest.  The bone should be rotated to find the maximum distance (Byrd and Adams 2003, #47B)", trigger = "hover"),
                        bsTooltip("Rad_09_as", "Minimum Diameter of the Diaphysis Distal to the Radial Tuberosity: The minimum shaft diameter anywhere distal to the radial tuberosity.  The bone may be rotated to find the minimum distance (Byrd and Adams 2003, #47C)", trigger = "hover"),
                        bsTooltip("Rad_10_as", "Breadth of the Distal Epiphysis: The maximum distance from the ulnar notch to the lateral aspect of the styloid process.  The medial protrusions (articular borders of the ulnar notch) are placed against the vertical endboard of the osteometric board (sliding calipers may also be used) and the movable portion is applied to the lateral surface of the styloid process to find the maximum breadth (Byrd and Adams 2015, #47E)", trigger = "hover"),
                        numericInput("Rad_01_as", label = "Rad_01", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_02_as", label = "Rad_02", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_03_as", label = "Rad_03", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_04_as", label = "Rad_04", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_05_as", label = "Rad_05", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_06_as", label = "Rad_06", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_07_as", label = "Rad_07", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_08_as", label = "Rad_08", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_09_as", label = "Rad_09", value = "", min=0,max=999,step=0.01),
                        numericInput("Rad_10_as", label = "Rad_10", value = "", min=0,max=999,step=0.01)
                    ),
                    conditionalPanel(condition = "input.bone_as == 'femur'",
                        bsTooltip("Fem_01_as", "Maximum Length of the Femur: The distance from the most proximal point on the head of the femur to the most distal point on the medial or lateral femoral condyle (Moore-Jansen et al. 1994, #60; Langley et al. 2016:78, #75)", trigger = "hover"),
                        bsTooltip("Fem_02_as", "Bicondylar Length of the Femur: The distance from the most proximal point on the head of the femur to a plane drawn between the inferior surfaces of the distal condyles (Moore-Jansen et al. 1994, #61; Langley et al. 2016:78, #76)", trigger = "hover"),
                        bsTooltip("Fem_03_as", "Epicondylar Breadth of the Femur: The distance between the two most projecting points on the epicondyles (Moore-Jansen et al. 1994, #63; Langley et al. 2016:79, #77)", trigger = "hover"),
                        bsTooltip("Fem_04_as", "Maximum Diameter of the Femur Head: The maximum diameter of the femur head measured on the border of the articular surface (Moore-Jansen et al. 1994, #63; Langley et al. 2016:79, #78)", trigger = "hover"),
                        bsTooltip("Fem_05_as", "Medial-Lateral (Transverse) Subtrochanteric Diameter of the Femur: The transverse diameter of the proximal portion of the diaphysis at the point of its greatest lateral expansion (Moore-Jansen et al. 1994, #65; Langley et al. 2016:79-80, #79)", trigger = "hover"),
                        bsTooltip("Fem_06_as", "Anterior-Posterior (Sagittal) Subtrochanteric Diameter of the Femur: The anterior-posterior diameter of the proximal end of the diaphysis measured perpendicular to the transverse diameter at the point of the greatest lateral expansion. This diameter is oriented perpendicular to the anterior surface of the femur neck (Moore-Jansen et al. 1994, #64; Langley et al. 2016:80, #80)", trigger = "hover"),
                        bsTooltip("Fem_07_as", "Anterior-Posterior (Sagittal) Midshaft Diameter: The distance between anterior and posterior surfaces measured approximately at the midpoint of the diaphysis, at the highest elevation of linea aspera (Moore-Jansen et al. 1994, #66)", trigger = "hover"),
                        bsTooltip("Fem_08_as", "Medial-Lateral (Transverse) Midshaft Diameter: The distance between the medial and lateral surfaces at midshaft, measured perpendicular to the anterior-posterior diameter (Moore-Jansen et al. 1994, #67)", trigger = "hover"),
                        bsTooltip("Fem_09_as", "Maximum Midshaft Diameter of the Femur: The maximum diameter of the femoral shaft taken at midshaft (Langley et al. 2016:80, #81)", trigger = "hover"),
                        bsTooltip("Fem_10_as", "Minimum Midshaft Diameter of the Femur: The minimum diameter of the femoral shaft taken at midshaft (Langley et al. 2016:80, #82)", trigger = "hover"),
                        bsTooltip("Fem_12_as", "Maximum Anterio-posterior Length of the Lateral Condyle: The distance between the most anterior and posterior points on the articular surface of the lateral condyle (Langley et al. 2016:80, #84)", trigger = "hover"),
                        bsTooltip("Fem_13_as", "Maximum Anterio-posterior Length of the Medial Condyle: The distance between the most anterior and posterior points on the articular surface of the medial condyle (Langley et al. 2016:80-81, #85)", trigger = "hover"),
                        bsTooltip("Fem_14_as", "Minimum Anterior-Posterior Diameter of the Diaphysis: The minimum anterior-posterior diameter anywhere along the diaphysis. The linea aspera and condyles should be utilized in order to orient the bone in anatomical position (use the condyles to orient) (Byrd and Adams 2003, #68A)", trigger = "hover"),
                        bsTooltip("Fem_15_as", "Minimum Medial-Lateral Diameter of the Diaphysis: The minimum medial-lateral diameter anywhere along the diaphysis.  The linea aspera and condyles should be utilized in order to orient the bone (should be taken in a perpendicular orientation to 68A) (Byrd and Adams 2003, #68B)", trigger = "hover"),
                        bsTooltip("Fem_16_as", "Minimum Superior-Inferior Neck Diameter: The minimum distance from the superior surface to the inferior surface on the femoral neck (Seidemann et al. 1998). Place caliper in the saddle of the neck (superior) and close inferior caliper arm, moving as necessary to find the minimum (Byrd and Adams 2015, #68D)", trigger = "hover"),
                        bsTooltip("Fem_17_as", "Maximum Diameter along the Linea Aspera: The maximum shaft diameter at any point along the linea aspera. As the bone should be rotated to obtain the maximum distance, the measurement does not necessarily have to include the linea aspera, though it likely will (Byrd and Adams 2003, #68E)", trigger = "hover"),
                        numericInput("Fem_01_as", label = "Fem_01", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_02_as", label = "Fem_02", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_03_as", label = "Fem_03", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_04_as", label = "Fem_04", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_05_as", label = "Fem_05", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_06_as", label = "Fem_06", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_07_as", label = "Fem_07", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_08_as", label = "Fem_08", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_09_as", label = "Fem_09", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_10_as", label = "Fem_10", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_12_as", label = "Fem_12", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_13_as", label = "Fem_13", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_14_as", label = "Fem_14", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_15_as", label = "Fem_15", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_16_as", label = "Fem_16", value = "", min=0,max=999,step=0.01),
                        numericInput("Fem_17_as", label = "Fem_17", value = "", min=0,max=999,step=0.01)
                    ),
                    conditionalPanel(condition = "input.bone_as == 'tibia'",
                        bsTooltip("Tib_01_as", "Length of the Tibia: The distance from the superior articular surface of the lateral condyle of the tibia to the tip of the medial malleolus (Moore-Jansen et al. 1994, #69; Langley et al. 2016:81, #86)", trigger = "hover"),
                        bsTooltip("Tib_02_as", "Maximum Proximal Epiphyseal Breadth of the Tibia: The maximum distance between the two most projecting point on the margins of the medial and lateral condyles of the proximal epiphysis (Moore-Jansen et al. 1994, #70; Langley et al. 2016:81, #87)", trigger = "hover"),
                        bsTooltip("Tib_03_as", "Maximum Distal Epiphyseal Breadth: The distance between the most medial point on the medial malleolus and the lateral surface of the distal epiphysis (Moore-Jansen et al. 1994, #71; Langley et al. 2016:81, #88)", trigger = "hover"),
                        bsTooltip("Tib_04_as", "Maximum Diameter at the Nutrient Foramen: The distance between the anterior crest and the posterior surface at the level of the nutrient foramen (Moore-Jansen et al. 1994, #72)", trigger = "hover"),
                        bsTooltip("Tib_05_as", "Transverse (Medial-Lateral) Diameter at the Nutrient Foramen: The straight line distance from the medial margin to the interosseous crest at the level of the nutrient foramen (Moore-Jansen et al. 1994, #73)", trigger = "hover"),
                        bsTooltip("Tib_07_as", "Maximum Midshaft Diameter of the Tibia: The maximum diameter of the tibial shaft taken at midshaft (Langley et al. 2016:81, #89)", trigger = "hover"),
                        bsTooltip("Tib_08_as", "Minimum Midshaft Diameter of the Tibia: The minimum diameter of the tibial shaft taken at midshaft (Langley et al. 2016:81, #90)", trigger = "hover"),
                        bsTooltip("Tib_10_as", "Maximum Anterior-Posterior Diameter Distal to the Popliteal Line: This measurement should be taken at the most distal point of the popliteal line where it intersects with the margin of the diaphysis. The calipers are rotated to find the maximum distance (this is the maximum diameter of the diaphysis at this point).  Note that the correct location may be difficult to determine in very gracile individuals (Byrd and Adams 2003, #74A)", trigger = "hover"),
                        bsTooltip("Tib_11_as", "Minimum Anterior-Posterior Diameter: Locate the minimum anterior-posterior distance at any point on the tibial shaft. Use the medial malleolus and anterior crest to orient the bone, particularly when torsion is present (Byrd and Adams 2003, #74B)", trigger = "hover"),
                        bsTooltip("Tib_12_as", "Maximum Anterior-Posterior Distance of the Distal Articular Surface: Locate the maximum anterior-posterior distance of the distal articular surface by viewing the element from the side to find the peaks of the articular surface and measuring the distance between them. Use the medial malleolus to orient the bone (Byrd and Adams 2015, #74F)", trigger = "hover"),
                        numericInput("Tib_01_as", label = "Tib_01", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_02_as", label = "Tib_02", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_03_as", label = "Tib_03", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_04_as", label = "Tib_04", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_05_as", label = "Tib_05", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_07_as", label = "Tib_07", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_08_as", label = "Tib_08", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_10_as", label = "Tib_10", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_11_as", label = "Tib_11", value = "", min=0,max=999,step=0.01),
                        numericInput("Tib_12_as", label = "Tib_12", value = "", min=0,max=999,step=0.01)
                    ),
                    conditionalPanel(condition = "input.bone_as == 'fibula'",
                        bsTooltip("Fib_01_as", "Maximum Length of the Fibula: The maximum distance between the most superior point on the fibular head and the most inferior point on the lateral malleolus (Moore-Jansen et al. 1994, #75; Langley et al. 2016:82, #92)", trigger = "hover"),
                        bsTooltip("Fib_02_as", "Maximum Diameter of the Fibula at Midshaft: The maximum diameter at the midshaft (Martin and Knussmann 1988:222, #2)", trigger = "hover"),
                        bsTooltip("Fib_03_as", "Maximum Diameter of the Diaphysis: This measurement should only be taken along the interosseous crest. Avoid measurements of the shaft near the epiphyses (Byrd and Adams 2015, #76A)", trigger = "hover"),
                        bsTooltip("Fib_04_as", "Minimum Diameter of the Diaphysis: The minimum distance at any point along the diaphysis (Byrd and Adams 2015, #76B)", trigger = "hover"),
                        bsTooltip("Fib_05_as", "Maximum Breadth at the Distal End: Place the one jaw of the caliper on the posterior portion (tubercle) and extend the other jaw to the opposite side (just above the malleolar articular surface) to find the maximum distance (Byrd and Adams 2015, #76C)", trigger = "hover"),
                        numericInput("Fib_01_as", label = "Fib_01", value = "", min=0,max=999,step=0.01),
                        numericInput("Fib_02_as", label = "Fib_02", value = "", min=0,max=999,step=0.01),
                        numericInput("Fib_03_as", label = "Fib_03", value = "", min=0,max=999,step=0.01),
                        numericInput("Fib_04_as", label = "Fib_04", value = "", min=0,max=999,step=0.01),
                        numericInput("Fib_05_as", label = "Fib_05", value = "", min=0,max=999,step=0.01)
                    )
                ),
                column(6,
                    textInput(inputId = 'case_id_as', label = 'Case ID', value = '2024-123')
                ),
                column(6,
                    textInput(inputId = 'analyst_as', label = 'Analyst', value = 'Trotter')
                ),
                column(6,
                    downloadButton("save_results_as","Save ", icon = icon("floppy-disk"))
                ),
                column(6,
                    actionButton("stature_associate_as","Associate", icon=icon("gears"))
                )
            ),
            tags$style(type = "text/css", "#stature_associate_as { width:100%; font-size:100%; background-color:#126a8f }"),
            tags$style(type = "text/css", "#save_results_as { width:100%; font-size:100%; background-color:#126a8f }"),
            width=2
        ), #sidebarPanel
        mainPanel(
            plotOutput('ggplot_as'),
            br(),
            DT::dataTableOutput('table_as')
            #tags$style(HTML('table.dataTable tr.selected td, table.dataTable tr.selected {box-shadow: inset 0 0 0 9999px #126a8f !important;}'))
        ) #mainPanel
    )#sidebarLayout
)